// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VocaChat.ConsoleApp.Data;

#nullable disable

namespace VocaChat.ConsoleApp.Migrations
{
    [DbContext(typeof(VocaChatDbContext))]
    [Migration("20260714000020_InitialAiAccountPersistence")]
    partial class InitialAiAccountPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("VocaChat.ConsoleApp.Models.AiAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeakingStyle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("AiAccounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_AiAccounts_IdentityDescription_MaxLength", "length(\"IdentityDescription\") <= 500");

                            t.HasCheckConstraint("CK_AiAccounts_Nickname_MaxLength", "length(\"Nickname\") <= 50");

                            t.HasCheckConstraint("CK_AiAccounts_Nickname_NotBlank", "length(trim(\"Nickname\")) > 0");

                            t.HasCheckConstraint("CK_AiAccounts_Personality_MaxLength", "length(\"Personality\") <= 200");

                            t.HasCheckConstraint("CK_AiAccounts_SpeakingStyle_MaxLength", "length(\"SpeakingStyle\") <= 200");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
