@VocaChat.WebApi_HostAddress = http://localhost:5205

GET {{VocaChat.WebApi_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{VocaChat.WebApi_HostAddress}}/api/ai-accounts
Accept: application/json

###

POST {{VocaChat.WebApi_HostAddress}}/api/ai-accounts
Content-Type: application/json

{
  "nickname": "ApiTestAccount",
  "identityDescription": "API 创建测试",
  "personality": "冷静",
  "speakingStyle": "简洁"
}

###

GET {{VocaChat.WebApi_HostAddress}}/api/group-chats
Accept: application/json

###

POST {{VocaChat.WebApi_HostAddress}}/api/group-chats
Content-Type: application/json

{
  "name": "API 测试群聊",
  "memberAiAccountIds": [
    "00000000-0000-0000-0000-000000000000"
  ]
}

###

POST {{VocaChat.WebApi_HostAddress}}/api/group-chats/00000000-0000-0000-0000-000000000000/members
Content-Type: application/json

{
  "aiAccountId": "00000000-0000-0000-0000-000000000000"
}

###

GET {{VocaChat.WebApi_HostAddress}}/api/group-chats/00000000-0000-0000-0000-000000000000/messages
Accept: application/json

###

POST {{VocaChat.WebApi_HostAddress}}/api/group-chats/00000000-0000-0000-0000-000000000000/messages
Content-Type: application/json

{
  "content": "大家好"
}

###
