// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VocaChat.Data;

#nullable disable

namespace VocaChat.Migrations
{
    [DbContext(typeof(VocaChatDbContext))]
    [Migration("20260718065544_AddAutonomousPrivateChatSessions")]
    partial class AddAutonomousPrivateChatSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("GroupChatMembers", b =>
                {
                    b.Property<Guid>("GroupChatId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AiAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupChatId", "AiAccountId");

                    b.HasIndex("AiAccountId");

                    b.ToTable("GroupChatMembers", (string)null);
                });

            modelBuilder.Entity("VocaChat.Models.AiAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarMediaId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hometown")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OnlineStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileCoverMediaId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeakingStyle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("VcNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.HasIndex("VcNumber")
                        .IsUnique();

                    b.ToTable("AiAccounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_AiAccounts_IdentityDescription_MaxLength", "length(\"IdentityDescription\") <= 500");

                            t.HasCheckConstraint("CK_AiAccounts_Nickname_MaxLength", "length(\"Nickname\") <= 50");

                            t.HasCheckConstraint("CK_AiAccounts_Nickname_NotBlank", "length(trim(\"Nickname\")) > 0");

                            t.HasCheckConstraint("CK_AiAccounts_Personality_MaxLength", "length(\"Personality\") <= 200");

                            t.HasCheckConstraint("CK_AiAccounts_SpeakingStyle_MaxLength", "length(\"SpeakingStyle\") <= 200");
                        });
                });

            modelBuilder.Entity("VocaChat.Models.AiAccountAutonomySettings", b =>
                {
                    b.Property<Guid>("AiAccountId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanInitiateGroupChats")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanInitiatePrivateChats")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanJoinGroupChats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InitiativeLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("AiAccountId");

                    b.ToTable("AiAccountAutonomySettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_AiAccountAutonomySettings_InitiativeLevel", "\"InitiativeLevel\" IN ('Low', 'Normal', 'High')");
                        });
                });

            modelBuilder.Entity("VocaChat.Models.AiAccountTag", b =>
                {
                    b.Property<Guid>("AiAccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("AiAccountId", "Type", "Value");

                    b.HasIndex("Type", "Value");

                    b.ToTable("AiAccountTags", (string)null);
                });

            modelBuilder.Entity("VocaChat.Models.AiRelationship", b =>
                {
                    b.Property<Guid>("FromAiAccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ToAiAccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Affinity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Familiarity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InteractionCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastInteractionAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Trust")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("FromAiAccountId", "ToAiAccountId");

                    b.HasIndex("ToAiAccountId");

                    b.ToTable("AiRelationships", null, t =>
                        {
                            t.HasCheckConstraint("CK_AiRelationships_Affinity", "\"Affinity\" BETWEEN -100 AND 100");

                            t.HasCheckConstraint("CK_AiRelationships_DifferentAccounts", "\"FromAiAccountId\" <> \"ToAiAccountId\"");

                            t.HasCheckConstraint("CK_AiRelationships_Familiarity", "\"Familiarity\" BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_AiRelationships_InteractionCount", "\"InteractionCount\" >= 0");

                            t.HasCheckConstraint("CK_AiRelationships_Trust", "\"Trust\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("VocaChat.Models.AutonomousInteractionSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowGroupChats")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowPrivateChats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AutonomousInteractionSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_AutonomousInteractionSettings_Frequency", "\"Frequency\" IN ('Low', 'Normal', 'High')");

                            t.HasCheckConstraint("CK_AutonomousInteractionSettings_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("VocaChat.Models.AutonomousPrivateChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedRounds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndReason")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InitiatorAiAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlannedMaximumRounds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PrivateChatId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipientAiAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InitiatorAiAccountId");

                    b.HasIndex("PrivateChatId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex("RecipientAiAccountId");

                    b.HasIndex("PrivateChatId", "StartedAt");

                    b.HasIndex("Status", "LastActivityAt");

                    b.ToTable("AutonomousPrivateChatSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_AutonomousPrivateChatSessions_DifferentParticipants", "\"InitiatorAiAccountId\" <> \"RecipientAiAccountId\"");

                            t.HasCheckConstraint("CK_AutonomousPrivateChatSessions_RoundLimits", "\"PlannedMaximumRounds\" BETWEEN 1 AND 4 AND \"CompletedRounds\" BETWEEN 0 AND \"PlannedMaximumRounds\"");

                            t.HasCheckConstraint("CK_AutonomousPrivateChatSessions_StateConsistency", "(\"Status\" = 0 AND \"EndReason\" IS NULL AND \"EndedAt\" IS NULL) OR (\"Status\" IN (1, 2, 3) AND \"EndReason\" IS NOT NULL AND \"EndedAt\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("VocaChat.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AiAccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContactGroupId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AiAccountId")
                        .IsUnique();

                    b.HasIndex("ContactGroupId");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("VocaChat.Models.ContactGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ContactGroups", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContactGroups_Name_MaxLength", "length(\"Name\") <= 50");

                            t.HasCheckConstraint("CK_ContactGroups_Name_NotBlank", "length(trim(\"Name\")) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d53f7a8-2d25-4e8a-bbad-82dc67384f01"),
                            CreatedAt = new DateTime(2026, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "默认分组",
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("VocaChat.Models.GroupChat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludesLocalUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GroupChats", null, t =>
                        {
                            t.HasCheckConstraint("CK_GroupChats_Name_MaxLength", "length(\"Name\") <= 100");

                            t.HasCheckConstraint("CK_GroupChats_Name_NotBlank", "length(trim(\"Name\")) > 0");
                        });
                });

            modelBuilder.Entity("VocaChat.Models.GroupMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupChatId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SenderAiAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SenderType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SenderAiAccountId");

                    b.HasIndex("GroupChatId", "SentAt", "Id");

                    b.ToTable("GroupMessages", null, t =>
                        {
                            t.HasCheckConstraint("CK_GroupMessages_Content_MaxLength", "length(\"Content\") <= 4000");

                            t.HasCheckConstraint("CK_GroupMessages_Content_NotBlank", "length(trim(\"Content\")) > 0");

                            t.HasCheckConstraint("CK_GroupMessages_SenderDisplayName_MaxLength", "length(\"SenderDisplayName\") <= 100");

                            t.HasCheckConstraint("CK_GroupMessages_SenderDisplayName_NotBlank", "length(trim(\"SenderDisplayName\")) > 0");

                            t.HasCheckConstraint("CK_GroupMessages_Sender_Consistency", "(\"SenderType\" = 0 AND \"SenderAiAccountId\" IS NULL) OR (\"SenderType\" = 1 AND \"SenderAiAccountId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("VocaChat.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorAiAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorAiAccountId");

                    b.HasIndex("CreatedAt", "Id");

                    b.ToTable("Posts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Posts_Content_MaxLength", "length(\"Content\") <= 2000");

                            t.HasCheckConstraint("CK_Posts_Content_NotBlank", "length(trim(\"Content\")) > 0");
                        });
                });

            modelBuilder.Entity("VocaChat.Models.PostComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AiAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PostId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AiAccountId");

                    b.HasIndex("PostId", "CreatedAt", "Id");

                    b.ToTable("PostComments", null, t =>
                        {
                            t.HasCheckConstraint("CK_PostComments_Content_NotBlank", "length(trim(\"Content\")) > 0");

                            t.HasCheckConstraint("CK_PostComments_SenderDisplayName_NotBlank", "length(trim(\"SenderDisplayName\")) > 0");
                        });
                });

            modelBuilder.Entity("VocaChat.Models.PostImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PostId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PostId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("PostImages", (string)null);
                });

            modelBuilder.Entity("VocaChat.Models.PostLike", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AiAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PostId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AiAccountId");

                    b.HasIndex("PostId")
                        .IsUnique()
                        .HasFilter("\"AiAccountId\" IS NULL");

                    b.HasIndex("PostId", "AiAccountId")
                        .IsUnique()
                        .HasFilter("\"AiAccountId\" IS NOT NULL");

                    b.ToTable("PostLikes", (string)null);
                });

            modelBuilder.Entity("VocaChat.Models.PrivateChat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FirstAiAccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SecondAiAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactId")
                        .IsUnique()
                        .HasFilter("\"ContactId\" IS NOT NULL");

                    b.HasIndex("SecondAiAccountId");

                    b.HasIndex("FirstAiAccountId", "SecondAiAccountId")
                        .IsUnique()
                        .HasFilter("\"FirstAiAccountId\" IS NOT NULL AND \"SecondAiAccountId\" IS NOT NULL");

                    b.ToTable("PrivateChats", null, t =>
                        {
                            t.HasCheckConstraint("CK_PrivateChats_Participants_Consistency", "(\"Kind\" = 0 AND \"ContactId\" IS NOT NULL AND \"FirstAiAccountId\" IS NULL AND \"SecondAiAccountId\" IS NULL) OR (\"Kind\" = 1 AND \"ContactId\" IS NULL AND \"FirstAiAccountId\" IS NOT NULL AND \"SecondAiAccountId\" IS NOT NULL AND \"FirstAiAccountId\" <> \"SecondAiAccountId\")");
                        });
                });

            modelBuilder.Entity("VocaChat.Models.PrivateMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AutonomousPrivateChatSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrivateChatId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SenderAiAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SenderType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SenderAiAccountId");

                    b.HasIndex("AutonomousPrivateChatSessionId", "SentAt", "Id")
                        .HasFilter("\"AutonomousPrivateChatSessionId\" IS NOT NULL");

                    b.HasIndex("PrivateChatId", "SentAt", "Id");

                    b.ToTable("PrivateMessages", null, t =>
                        {
                            t.HasCheckConstraint("CK_PrivateMessages_Content_NotBlank", "length(trim(\"Content\")) > 0");

                            t.HasCheckConstraint("CK_PrivateMessages_SenderDisplayName_NotBlank", "length(trim(\"SenderDisplayName\")) > 0");

                            t.HasCheckConstraint("CK_PrivateMessages_Sender_Consistency", "(\"SenderType\" = 0 AND \"SenderAiAccountId\" IS NULL) OR (\"SenderType\" = 1 AND \"SenderAiAccountId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("GroupChatMembers", b =>
                {
                    b.HasOne("VocaChat.Models.AiAccount", null)
                        .WithMany()
                        .HasForeignKey("AiAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VocaChat.Models.GroupChat", null)
                        .WithMany()
                        .HasForeignKey("GroupChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VocaChat.Models.AiAccountAutonomySettings", b =>
                {
                    b.HasOne("VocaChat.Models.AiAccount", null)
                        .WithOne()
                        .HasForeignKey("VocaChat.Models.AiAccountAutonomySettings", "AiAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VocaChat.Models.AiAccountTag", b =>
                {
                    b.HasOne("VocaChat.Models.AiAccount", null)
                        .WithMany("Tags")
                        .HasForeignKey("AiAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VocaChat.Models.AiRelationship", b =>
                {
                    b.HasOne("VocaChat.Models.AiAccount", "FromAiAccount")
                        .WithMany()
                        .HasForeignKey("FromAiAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VocaChat.Models.AiAccount", "ToAiAccount")
                        .WithMany()
                        .HasForeignKey("ToAiAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromAiAccount");

                    b.Navigation("ToAiAccount");
                });

            modelBuilder.Entity("VocaChat.Models.AutonomousPrivateChatSession", b =>
                {
                    b.HasOne("VocaChat.Models.AiAccount", null)
                        .WithMany()
                        .HasForeignKey("InitiatorAiAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VocaChat.Models.PrivateChat", null)
                        .WithMany()
                        .HasForeignKey("PrivateChatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VocaChat.Models.AiAccount", null)
                        .WithMany()
                        .HasForeignKey("RecipientAiAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VocaChat.Models.Contact", b =>
                {
                    b.HasOne("VocaChat.Models.AiAccount", "AiAccount")
                        .WithOne()
                        .HasForeignKey("VocaChat.Models.Contact", "AiAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VocaChat.Models.ContactGroup", "ContactGroup")
                        .WithMany()
                        .HasForeignKey("ContactGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiAccount");

                    b.Navigation("ContactGroup");
                });

            modelBuilder.Entity("VocaChat.Models.GroupMessage", b =>
                {
                    b.HasOne("VocaChat.Models.GroupChat", null)
                        .WithMany()
                        .HasForeignKey("GroupChatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VocaChat.Models.AiAccount", null)
                        .WithMany()
                        .HasForeignKey("SenderAiAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VocaChat.Models.Post", b =>
                {
                    b.HasOne("VocaChat.Models.AiAccount", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorAiAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("VocaChat.Models.PostComment", b =>
                {
                    b.HasOne("VocaChat.Models.AiAccount", null)
                        .WithMany()
                        .HasForeignKey("AiAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VocaChat.Models.Post", null)
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VocaChat.Models.PostImage", b =>
                {
                    b.HasOne("VocaChat.Models.Post", null)
                        .WithMany("Images")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VocaChat.Models.PostLike", b =>
                {
                    b.HasOne("VocaChat.Models.AiAccount", null)
                        .WithMany()
                        .HasForeignKey("AiAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VocaChat.Models.Post", null)
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VocaChat.Models.PrivateChat", b =>
                {
                    b.HasOne("VocaChat.Models.Contact", "Contact")
                        .WithOne()
                        .HasForeignKey("VocaChat.Models.PrivateChat", "ContactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VocaChat.Models.AiAccount", "FirstAiAccount")
                        .WithMany()
                        .HasForeignKey("FirstAiAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VocaChat.Models.AiAccount", "SecondAiAccount")
                        .WithMany()
                        .HasForeignKey("SecondAiAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Contact");

                    b.Navigation("FirstAiAccount");

                    b.Navigation("SecondAiAccount");
                });

            modelBuilder.Entity("VocaChat.Models.PrivateMessage", b =>
                {
                    b.HasOne("VocaChat.Models.AutonomousPrivateChatSession", null)
                        .WithMany()
                        .HasForeignKey("AutonomousPrivateChatSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VocaChat.Models.PrivateChat", null)
                        .WithMany()
                        .HasForeignKey("PrivateChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VocaChat.Models.AiAccount", null)
                        .WithMany()
                        .HasForeignKey("SenderAiAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VocaChat.Models.AiAccount", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("VocaChat.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Images");

                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
