// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VocaChat.Data;

#nullable disable

namespace VocaChat.Migrations
{
    [DbContext(typeof(VocaChatDbContext))]
    partial class VocaChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("GroupChatMembers", b =>
                {
                    b.Property<Guid>("GroupChatId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AiAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupChatId", "AiAccountId");

                    b.HasIndex("AiAccountId");

                    b.ToTable("GroupChatMembers", (string)null);
                });

            modelBuilder.Entity("VocaChat.Models.AiAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeakingStyle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("AiAccounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_AiAccounts_IdentityDescription_MaxLength", "length(\"IdentityDescription\") <= 500");

                            t.HasCheckConstraint("CK_AiAccounts_Nickname_MaxLength", "length(\"Nickname\") <= 50");

                            t.HasCheckConstraint("CK_AiAccounts_Nickname_NotBlank", "length(trim(\"Nickname\")) > 0");

                            t.HasCheckConstraint("CK_AiAccounts_Personality_MaxLength", "length(\"Personality\") <= 200");

                            t.HasCheckConstraint("CK_AiAccounts_SpeakingStyle_MaxLength", "length(\"SpeakingStyle\") <= 200");
                        });
                });

            modelBuilder.Entity("VocaChat.Models.GroupChat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GroupChats", null, t =>
                        {
                            t.HasCheckConstraint("CK_GroupChats_Name_MaxLength", "length(\"Name\") <= 100");

                            t.HasCheckConstraint("CK_GroupChats_Name_NotBlank", "length(trim(\"Name\")) > 0");
                        });
                });

            modelBuilder.Entity("VocaChat.Models.GroupMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupChatId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SenderAiAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SenderType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SenderAiAccountId");

                    b.HasIndex("GroupChatId", "SentAt", "Id");

                    b.ToTable("GroupMessages", null, t =>
                        {
                            t.HasCheckConstraint("CK_GroupMessages_Content_MaxLength", "length(\"Content\") <= 4000");

                            t.HasCheckConstraint("CK_GroupMessages_Content_NotBlank", "length(trim(\"Content\")) > 0");

                            t.HasCheckConstraint("CK_GroupMessages_SenderDisplayName_MaxLength", "length(\"SenderDisplayName\") <= 100");

                            t.HasCheckConstraint("CK_GroupMessages_SenderDisplayName_NotBlank", "length(trim(\"SenderDisplayName\")) > 0");

                            t.HasCheckConstraint("CK_GroupMessages_Sender_Consistency", "(\"SenderType\" = 0 AND \"SenderAiAccountId\" IS NULL) OR (\"SenderType\" = 1 AND \"SenderAiAccountId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("GroupChatMembers", b =>
                {
                    b.HasOne("VocaChat.Models.AiAccount", null)
                        .WithMany()
                        .HasForeignKey("AiAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VocaChat.Models.GroupChat", null)
                        .WithMany()
                        .HasForeignKey("GroupChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VocaChat.Models.GroupMessage", b =>
                {
                    b.HasOne("VocaChat.Models.GroupChat", null)
                        .WithMany()
                        .HasForeignKey("GroupChatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VocaChat.Models.AiAccount", null)
                        .WithMany()
                        .HasForeignKey("SenderAiAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
